version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tutoring-school
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1018

  spring-app:
    image: tutoring-school:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/tutoring-school
    depends_on:
      - postgres-db